== Quickstart

:Author: Jeff Rogers
:Email: jbrogers63@gmail.com

.Clone the repo and run the bootstrap script to setup:
[source,bash]
git clone https://github.com/jbrogers63/ansible-ca
cd ansible-ca
bash scripts/bootstrap.sh

.Alternatively, give your CA a name (useful to keep a root CA separate from intermediate CAs):
[source,bash]
CA="Root CA" bash scripts/bootstrap.sh

== Basic Setup

In order to setup a certificate authority, one needs to add a vars file in

[source,bash]
inventory/group_vars/all

With the following contents filled in (to match your environment):

[source,yaml]
---
ca:
  path: "/path/to/your/root/ca/folder"
  common_name: "Example.org Root CA"
  organization_name: "example.org"
  email_address: "admin@example.org"
  country_name: "US"
  key_usage:
    - keyCertSign
  basic_constraints:
    - "CA:TRUE"

Then, do the following:
[source,bash]
bash scripts/setup-ca.sh

That will create a self-signed certificate in the configured directory that can be used to sign certificates.

== Requirements

To generate certificates on remote hosts, the following dependency needs to be installed:

- cryptography python package

.On Debian/Ubuntu and alternatives:
[source,bash]
apt install python3-cryptography

.On RedHat and alternatives:
[source,bash]
dnf install python3-cryptography

.On FreeBSD:
[source,bash]
pkg install security/py-cryptography

.On OpenBSD:
[source,bash]
pkg_add security/py-cryptography
