== Quickstart

:Author: Jeff Rogers
:Email: jbrogers63@gmail.com

.Download a release version, unpack it, and run the bootstrap script to setup:
[source,bash]
wget https://github.com/jbrogers63/ansible-ca/archive/refs/tags/ansible-ca-0.1.0.tar.gz
tar -xf ansible-ca-0.1.0.tar.gz
cd ansible-ca
bash scripts/bootstrap.sh

.Alternatively, give your CA a name (useful to keep a root CA separate from intermediate CAs):
[source,bash]
CA="Root CA" bash scripts/bootstrap.sh

== Basic Setup

In order to setup a certificate authority, one needs to add a vars file in

[source,bash]
inventory/group_vars/all

With the following contents filled in (to match your environment):

[source,yaml]
---
ca:
  path: "/path/to/your/root/ca/folder"
  common_name: "Example.org Root CA"
  organization_name: "example.org"
  email_address: "admin@example.org"
  country_name: "US"
  key_usage:
    - keyCertSign
  basic_constraints:
    - "CA:TRUE"
cert_path: "/etc/ssl/mycerts"

Create a hosts file in:

[source,ini]
----
[all]
host1.local
host2.local
host3.local
----

Then, do the following:
[source,bash]
bash scripts/setup-ca.sh

That will create a self-signed certificate in the configured directory that can be used to sign certificates.

Create individual host certificates like so:

[source,bash]
bash scripts/setup-host.sh -H host1.local

== Requirements

To generate certificates on remote hosts, the following dependency needs to be installed:

- cryptography python package

.On Debian/Ubuntu and alternatives:
[source,bash]
apt install python3-cryptography

.On RedHat and alternatives:
[source,bash]
dnf install python3-cryptography

.On FreeBSD:
[source,bash]
pkg install security/py-cryptography

.On OpenBSD:
[source,bash]
pkg_add security/py-cryptography


== Customizing the CA

All variables that need to be overridden can be placed in the inventory/group_vars/all file.  For example, if additional subjectAlternativeNames are needed, add them as a list to inventory/group_vars/all:

[source,yaml]
san_patterns:
  - "DNS:{{ ansible_fqdn }}"
  - "DNS:{{ ansible_default_ipv4.address }}"

.By default, the following variables are pre-configured:
* ansible_fqdn var is already added to the san_patterns list.
* not_before is set to "yesterday" (-1 day from today)
* not after is set to the same day one year from now (+364 days from today)

